name: zing_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.4
  cupertino_icons: ^1.0.2
  fl_chart: ^0.61.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
